name: Package & Push Helm Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-development-helm-chart:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ["cluster-autoscaler"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart to GHCR
        working-directory: charts
        run: |
          helm package ${{ matrix.chart }}
          helm push ${{ matrix.chart }}-*.tgz oci://ghcr.io/siliconsheep/helm-charts